// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHCp8kPKoh2gmeBv_Xm_rbc6RdEUwUiW8',
    appId: '1:473271774891:web:5b03b8ce1d5c8d18d3d1ee',
    messagingSenderId: '473271774891',
    projectId: 'case-connectinno',
    authDomain: 'case-connectinno.firebaseapp.com',
    storageBucket: 'case-connectinno.firebasestorage.app',
    measurementId: 'G-SY5PDVDZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcNeOZ89_6v61XIjnucJAtITd7QCixJ_A',
    appId: '1:473271774891:android:d93869c4e96baf8fd3d1ee',
    messagingSenderId: '473271774891',
    projectId: 'case-connectinno',
    storageBucket: 'case-connectinno.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-sBXQFs8i63YZQib-liFgNhcMAeIS3A',
    appId: '1:473271774891:ios:e118934ec2e31ebdd3d1ee',
    messagingSenderId: '473271774891',
    projectId: 'case-connectinno',
    storageBucket: 'case-connectinno.firebasestorage.app',
    iosBundleId: 'com.example.caseConnectinno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-sBXQFs8i63YZQib-liFgNhcMAeIS3A',
    appId: '1:473271774891:ios:e118934ec2e31ebdd3d1ee',
    messagingSenderId: '473271774891',
    projectId: 'case-connectinno',
    storageBucket: 'case-connectinno.firebasestorage.app',
    iosBundleId: 'com.example.caseConnectinno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHCp8kPKoh2gmeBv_Xm_rbc6RdEUwUiW8',
    appId: '1:473271774891:web:ff417bf481856e51d3d1ee',
    messagingSenderId: '473271774891',
    projectId: 'case-connectinno',
    authDomain: 'case-connectinno.firebaseapp.com',
    storageBucket: 'case-connectinno.firebasestorage.app',
    measurementId: 'G-J3922863HY',
  );
}
